# Generated by Django 2.2 on 2020-06-12 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=35)),
                ('email', models.CharField(max_length=30)),
                ('zipcode', models.CharField(max_length=5)),
                ('pw', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=20)),
                ('zipcode', models.CharField(max_length=5)),
                ('pw', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('patrons', models.ManyToManyField(related_name='patrons', to='gamer_app.User')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('player', models.CharField(max_length=2)),
                ('gametype', models.CharField(max_length=40)),
                ('desc', models.CharField(max_length=250)),
                ('cover', models.FileField(upload_to='covers')),
                ('fav', models.ManyToManyField(related_name='games', to='gamer_app.User')),
            ],
        ),
    ]
