# Generated by Django 2.2 on 2020-06-13 20:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gamer_app', '0003_auto_20200612_2144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='fav',
        ),
        migrations.AddField(
            model_name='game',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='game',
            name='poster',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='posters', to='gamer_app.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('player', models.CharField(max_length=2)),
                ('gametype', models.CharField(max_length=40)),
                ('desc', models.CharField(max_length=250)),
                ('cover', models.ImageField(upload_to='covers/')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('fav', models.ManyToManyField(related_name='games', to='gamer_app.User')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to='gamer_app.Merchant')),
            ],
        ),
    ]
