# Generated by Django 2.2 on 2020-06-13 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamer_app', '0004_auto_20200613_2000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='merchant',
            old_name='patrons',
            new_name='patron',
        ),
    ]
