# Generated by Django 2.2 on 2020-06-14 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamer_app', '0005_auto_20200613_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='photo',
            field=models.ImageField(null=True, upload_to='photos/'),
        ),
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(null=True, upload_to='photos/'),
        ),
    ]
