# Generated by Django 2.2 on 2020-06-14 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamer_app', '0006_auto_20200614_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchant',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='user',
            name='photo',
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('merch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='merchant', to='gamer_app.Merchant')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gamer', to='gamer_app.User')),
            ],
        ),
    ]
