# Generated by Django 2.2 on 2020-06-14 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamer_app', '0007_auto_20200614_1850'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
