# Generated by Django 2.2 on 2020-06-05 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_app', '0002_auto_20200605_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='players',
            field=models.IntegerField(),
        ),
    ]
