# Generated by Django 2.2 on 2020-06-05 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_app', '0003_auto_20200605_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='players',
            field=models.CharField(max_length=2),
        ),
    ]
