# Generated by Django 2.2 on 2020-06-05 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board_app', '0004_auto_20200605_2310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='players',
            new_name='player',
        ),
    ]
