# Generated by Django 2.2 on 2020-06-11 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board_app', '0005_auto_20200605_2310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchant',
            name='fav',
        ),
        migrations.AddField(
            model_name='merchant',
            name='patron',
            field=models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, related_name='users', to='board_app.User'),
            preserve_default=False,
        ),
    ]
