# Generated by Django 2.2 on 2020-06-11 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_app', '0006_auto_20200611_2026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchant',
            name='patron',
        ),
        migrations.AddField(
            model_name='merchant',
            name='patrons',
            field=models.ManyToManyField(related_name='stores', to='board_app.User'),
        ),
    ]
