# Generated by Django 2.2 on 2020-06-11 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board_app', '0007_auto_20200611_2030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchant',
            name='patrons',
        ),
    ]
