# Generated by Django 2.2 on 2020-06-11 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('zipcode', models.CharField(max_length=5)),
                ('pw', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=20)),
                ('zipcode', models.CharField(max_length=5)),
                ('pw', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('patrons', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patrons', to='boardgame_app.User')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('player', models.CharField(max_length=2)),
                ('gametype', models.CharField(max_length=40)),
                ('desc', models.CharField(max_length=250)),
                ('fav', models.ManyToManyField(related_name='games', to='boardgame_app.User')),
            ],
        ),
    ]
