# Generated by Django 2.2 on 2020-06-12 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardgame_app', '0002_auto_20200611_2244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchant',
            name='patrons',
        ),
        migrations.AddField(
            model_name='merchant',
            name='patrons',
            field=models.ManyToManyField(related_name='patrons', to='boardgame_app.User'),
        ),
    ]
