# Generated by Django 2.2 on 2020-06-12 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardgame_app', '0003_auto_20200612_0431'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='poster',
            field=models.ForeignKey(default='user', on_delete='models.CASCADE', related_name='poster', to='boardgame_app.User'),
            preserve_default=False,
        ),
    ]
